"""Add console to database

Revision ID: 289092e038db
Revises: 10a5028dd290
Create Date: 2021-07-20 17:08:21.978143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '289092e038db'
down_revision = '10a5028dd290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('console',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('console')
    # ### end Alembic commands ###
