"""plural-table-names

Revision ID: 52d9c48dc5c1
Revises: 
Create Date: 2021-08-05 17:53:14.299943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52d9c48dc5c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment')
    op.drop_table('owner')
    op.drop_table('pet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('pet_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('species', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('breed', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pet_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('owner',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('owner_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='owner_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('appointment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('time', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], name='appointment_owner_id_fkey'),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], name='appointment_pet_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='appointment_pkey')
    )
    # ### end Alembic commands ###
